### ISSUE TITLE
error on init

### ISSUE THREAD

**Issue by tjomtek** [mymi14s/frappe_random#3]
From Command :
bench init --frappe-branch=version-13 --python=python3.8 frappe-bench

warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages…
[1/3] ⠄ node-sass
[2/3] ⠄ core-js
error /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/node-sass
Output:
Building: /usr/bin/node /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli ‘/usr/bin/node’,
gyp verb cli ‘/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js’,
gyp verb cli ‘rebuild’,
gyp verb cli ‘–verbose’,
gyp verb cli ‘–libsass_ext=’,
gyp verb cli ‘–libsass_cflags=’,
gyp verb cli ‘–libsass_ldflags=’,
gyp verb cli ‘–libsass_library=’
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.20.0 | linux | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing “build” directory
gyp verb command configure []
gyp verb check python checking for Python executable “python2” in the PATH
gyp verb which failed Error: not found: python2
gyp verb which failed at getNotFoundError (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:13:12)
gyp verb which failed at F (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:68:19)
gyp verb which failed at E (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb which failed at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb which failed python2 Error: not found: python2
gyp verb which failed at getNotFoundError (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:13:12)
gyp verb which failed at F (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:68:19)
gyp verb which failed at E (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb which failed at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb which failed code: ‘ENOENT’
gyp verb which failed }
gyp verb check python checking for Python executable “python” in the PATH
gyp verb which failed Error: not found: python
gyp verb which failed at getNotFoundError (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:13:12)
gyp verb which failed at F (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:68:19)
gyp verb which failed at E (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb which failed at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb which failed python Error: not found: python
gyp verb which failed at getNotFoundError (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:13:12)
gyp verb which failed at F (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:68:19)
gyp verb which failed at E (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb which failed at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb which failed at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb which failed code: ‘ENOENT’
gyp verb which failed }
gyp ERR! configure error
gyp ERR! stack Error: Can’t find Python executable “python”, you can set the PYTHON env variable.
gyp ERR! stack at PythonFinder.failNoPython (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack at PythonFinder. (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack at F (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:68:16)
gyp ERR! stack at E (/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
gyp ERR! stack at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
gyp ERR! stack at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
gyp ERR! stack at /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
gyp ERR! stack at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 5.15.0-1013-oracle
gyp ERR! command “/usr/bin/node” “/home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js” “rebuild” “–verbose” “–libsass_ext=” “–libsass_cflags=” “–libsass_ldflags=” “–libsass_library=”
gyp ERR! cwd /home/erpnxtadmin/frappe-bench/apps/frappe/node_modules/node-sass
gyp ERR! node -v v14.20.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

Traceback (most recent call last):
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/commands/make.py”, line 68, in init
init(
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/utils/render.py”, line 105, in wrapper_fn
return fn(*args, **kwargs)
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/utils/system.py”, line 79, in init
get_app(
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/app.py”, line 432, in get_app
app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/utils/render.py”, line 126, in wrapper_fn
return fn(*args, **kwargs)
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/app.py”, line 230, in install
install_app(
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/app.py”, line 569, in install_app
bench.run(“yarn install”, cwd=app_path)
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/bench.py”, line 47, in run
return exec_cmd(cmd, cwd=cwd or self.cwd)
File “/home/erpnxtadmin/.local/lib/python3.8/site-packages/bench/utils/init.py”, line 155, in exec_cmd
raise CommandFailedError
bench.exceptions.CommandFailedError

ERROR: There was a problem while creating frappe-bench

**Comment by tjomtek** [comment]
git clone https://github.com/frappe/bench bench-repo
sudo pip3 install -e bench-repo
sudo pip3 install frappe-bench
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
sudo apt install python3.10
sudo apt install python3.10-dev
bench init frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13
